### PR TITLE
feat!: esbuild as a peer dependency

### LINKED ISSUE #25: Externalizing esbuild as a peer dependency
esbuild is in active development and receives consistent updates.

We should consider making it a peer dependency (eg. like [svgo-loader](https://github.com/rpominov/svgo-loader)) so that users can use the latest esbuild independently of this module.

### PR DESCRIPTION
**Pull request by privatenumber**
This allows users to upgrade esbuild independently of esbuild-loader.

This is great because esbuild has a new release [every other day](https://github.com/evanw/esbuild/releases).

Unfortunately, this is going to be a breaking change.

Hope to queue this with some other BCs.

Closes #25

### CODE REVIEW

**Comment by airhorns** [comment]
This makes a lot of sense to me, would love to get this in so esbuild can be upgraded independently!

**Comment by airhorns** [comment]
Oh, I think this commit is actually on master already and this PR can be closed. Would be dandy to get a release with it out!

**Comment by privatenumber** [comment]
Still holding this because I want to batch it with another breaking change, and also waiting for esbuild v1 because I imagine there's going to be a breaking change there.

Do you want me to do a dependency upgrade release instead?

Alternatively, if you're using yarn, you can use the [`resolutions` feature](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/).

**Comment by airhorns** [comment]
Oh sorry I was looking at the wrong branch on the root page 😅 

No rush, I am just using `resolutions` :)

**Comment by privatenumber** [comment]
Adding a note that this might not be a good idea to release till esbuild is v1 (stable) because they can still technically do breaking changes (they did a breaking change on the Node API recently).

**Pull request merged**
