### PR TITLE
fix(tsconfig): support multiple tsconfigs to be specified

### LINKED ISSUE #325: Doesn't work well with esbuild 0.18.x and inherited `tsconfig.json` and `experimentalDecorators`
### Bug description

esbuild 0.18.x changed how esbuild uses tsconfig files: https://github.com/evanw/esbuild/releases/tag/v0.18.0

Which seems to conflict or somehow interfere with how this plugin parses the `tsconfig.json`. Can we now just pass the `tsconfig.json` file provided directly to esbuild?

### Minimal reproduction link

https://github.com/gitkraken/vscode-gitlens

### Environment

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 14.34 GB / 31.92 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    esbuild-loader: 3.0.1 => 3.0.1
    webpack: 5.86.0 => 5.86.0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

### PR DESCRIPTION
**Pull request by eamodio**
Avoids reusing a previous cache if the `tsconfig` prop is different

Refs: #325

### CODE REVIEW

**Comment by privatenumber** [comment]
Is this happening because you have multiple tsconfigs?

Can you add a test?

**Comment by eamodio** [comment]
Yeah, I have 3 parallel builds, and each has its own `tsconfig`.

As for adding a test -- any guidance there?

**Comment by privatenumber** [comment]
Specifically, it sounds like your issue is with multiple tsconfig.json files. The bug sounds like it could happen with one Webpack build, irrelevant of parallel.

I would just follow the existing tests and add multiple tsconfig files.

**Comment by eamodio** [comment]
I tried getting a test setup, but am not having any luck even getting the other tests to work -- the webpack4/5 ones work, but after that I get failures:

```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (c:\Users\Eric\code\eamodio\esbuild-loader\node_modules\.pnpm\webpack@4.46.0_webpack-cli@4.10.0\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (c:\Users\Eric\code\eamodio\esbuild-loader\node_modules\.pnpm\webpack@4.46.0_webpack-cli@4.10.0\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (c:\Users\Eric\code\eamodio\esbuild-loader\node_modules\.pnpm\webpack@4.46.0_webpack-cli@4.10.0\node_modules\webpack\lib\NormalModule.js:471:10)
    at <anonymous> (c:\Users\Eric\code\eamodio\esbuild-loader\node_modules\.pnpm\webpack@4.46.0_webpack-cli@4.10.0\node_modules\webpack\lib\NormalModule.js:503:5)
    at <anonymous> (c:\Users\Eric\code\eamodio\esbuild-loader\node_modules\.pnpm\webpack@4.46.0_webpack-cli@4.10.0\node_modules\webpack\lib\NormalModule.js:358:12)
    at <anonymous> (c:\Users\Eric\code\eamodio\esbuild-loader\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:373:3)
    at iterateNormalLoaders (c:\Users\Eric\code\eamodio\esbuild-loader\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Function.<anonymous> (c:\Users\Eric\code\eamodio\esbuild-loader\node_modules\.pnpm\loader-runner@2.4.0\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.1
 ELIFECYCLE  Test failed. See above for more details.
```

There are also no docs for setting things up, running builds or tests, so I'm guessing I've set it up wrong (or its my Node version). 

If you could help set this up it would be greatly appreciated. Thanks!

**Comment by privatenumber** [comment]
GitHub Actions runs the tests and they're passing.

Take a look at the setup:
https://github.com/esbuild-kit/esbuild-loader/blob/3ee8b5765aa229cf46c28898a8c22a71d9f5e6e4/.github/workflows/test.yml#L36-L39

**Comment by eamodio** [comment]
As I mentioned, I've tried and spent a bunch of time on it and haven't been able to get it working. Also, I'm unsure about how best to observe this change in a unit test, as the only way I could see this is to build something (maybe even the same thing) with different tsconfigs which would result in differing outputs.

And to be completely honest, I don't have more time to spend on this issue. Hopefully this can either be merged without a test, or that you or another contributor could create it.

**Comment by eamodio** [comment]
I was finally able to get a test working with an observable output change. The test fails before my fix and succeeds after it. It also proved that it doesn't have to do with parallel builds just multiple tsconfigs -- which IMO makes this bug even worse.

**Comment by eamodio** [comment]
@privatenumber hopefully this can be merged now.

**Comment by eamodio** [comment]
@privatenumber Not to bug you, but I would love to know if they can be merged soon. If not please let me know as this is blocking our esbuild upgrade, and I'll have to publish a fork with the fix -- which is fine, I just don't want to do that work if this will be merged soon. Thanks!

**Comment by eamodio** [comment]
@privatenumber Can this get merged please?

**Comment by privatenumber** [comment]
Thanks for the PR.

I removed the caching for a bit. I plan on implementing it in get-tsconfig.

**Comment by privatenumber** [comment]
## BREAKING CHANGE: tsconfig passed in by path is now applied regardless of whether it matches

**Comment by privatenumber** [comment]
Preparing the v4 release. Would you mind helping test?

```sh
npm install -D 'esbuild-kit/esbuild-loader#npm/v4'
```

**Comment by eamodio** [comment]
Tried it out and works in my testing! TY

**Pull request merged**
