### PR TITLE
chore: upgrade esbuild to 0.9.2

### PR DESCRIPTION
**Pull request by itsoli**
Upgrade to ESBuild 0.9.2. Incorporates necessary changes for the removal of the `esbuild.startService()` API which makes the ESBuildPlugin obsolete.
Some tests are failing due to ESBuild emitting different output in the updated version (source maps and minification). The snapshots need to be updated for the new version.
Linting fails but the problems are unrelated to this PR.

### CODE REVIEW

**Comment by privatenumber** [comment]
Thanks for the PR @itsoli 

I'd like to avoid the breaking change so let's make the ESBuildPlugin a no-op that logs:

> `ESBuildPlugin` has been deprecated and is no longer required for usage. It will be removed in the next major release. Please refer to the docs and release notes for more info

Before updating the test snapshots here, I'm going to update Webpack in `develop` since there are some bigger changes there.

Update:
Finished updating and merged.

**Comment by itsoli** [comment]
Thanks for swiftly getting this merged!

**Comment by cjones26** [comment]
> Thanks for the PR @itsoli
> 
> I'd like to avoid the breaking change so let's make the ESBuildPlugin a no-op that logs:
> 
> > `ESBuildPlugin` has been deprecated and is no longer required for usage. It will be removed in the next major release. Please refer to the docs and release notes for more info
> 
> Before updating the test snapshots here, I'm going to update Webpack in `develop` since there are some bigger changes there.
> 
> Update:
> Finished updating and merged.

I'm confused by this--why is the plugin no longer required?  I was testing out the CRACO ESBuild plugin (https://github.com/pradel/create-react-app-esbuild) and noticed this no-op error message.  Can someone elaborate here?  Thanks!

**Comment by privatenumber** [comment]
@cjones26 I explained in the release notes [here](https://github.com/privatenumber/esbuild-loader/releases/tag/v2.10.0)

**Pull request merged**
