### PR TITLE
feat: Minification and more

### PR DESCRIPTION
**Pull request by privatenumber**
### Issue
https://github.com/egoist/esbuild-loader/issues/2

### Changes

- Refactored the organization of src files by splitting up the plugin, loader, and minify plugin into separate files
- **Loader changes**
  - **BC** Source-map option now uses `this.sourceMap` instead of reading from `options`. This flag is toggled on by Webpack if `devtool` uses source-map or if `SourceMapDevToolPlugin` is used
  - **BC** `loader` is now passed in. I think it makes more sense for the user to set this, especially in cases where there's some Webpack magic happening and it's hard to detect the actual file type (eg. `.vue` files). With this change, a user can configure `esbuild-loader` more predictably:
    ```js
    [
      {
        test: /\.js$/,
        loader: 'esbuild-loader',
      },
      {
        test: /\.tsx$/,
        loader: 'esbuild-loader',
        options: {
          loader: 'tsx'
        }
      },
      {
        test: /\.json$/,
        loader: 'esbuild-loader',
        options: {
          loader: 'json'
        }
      },
    ]
    ```

- **Added `MinifyPlugin`**
  - Minifies files async (parallel)
  - Source-map setting reads from `devtool` or `sourcemap` option. Plugins don't seem to have access to Webpack's `sourceMap` flag

- **Tests**
  - Virtual file-system for testing
  - Minify tests
  - Loader tests (loaders, targets, source-maps)

- **README.md update** TBD. I understand if this PR is not mergable considering these are dramatic changes with BCs. But if they're mergable, I can update the README to reflect that, otherwise, I'll re-package it.

### CODE REVIEW

**Review by egoist — APPROVED** [review]
LGTM 👌🏻

**Comment by privatenumber** [comment]
Cool, I updated the README!

Btw, can I help maintain this project?

**Comment by egoist** [comment]
Sure, just added you as a collaborator.

**Comment by privatenumber** [comment]
Thanks :)

I can merge this now if you'd like, but I don't think I'll be able to cut a release because of npm.

Edit:

I see you have semantic release setup.
I'm not familiar with how to it yet, but I believe I have to mark this as a BC so it does a major release.
Will look into it tomorrow.

Are you okay with me releasing this whenever?

**Comment by egoist** [comment]
@privatenumber yes, just write something starting with `BREAKING CHANGE:` in the commit details when you squash and merge it, then it will receive a major version bump:

Screenshot_20200802-010158__01

**Comment by privatenumber** [comment]
Great, thanks!

I'm running some final tests in a few large codebases I'm in. Will release soon 👍

**Comment by privatenumber** [comment]
Two findings:
- The loader causes a strange behavior in my codebase that I haven't been able to pin down. I have assets outputting to `js/[name].[chunkhash].en.js`, but the `[name]` gets replaced with a number (guessing asset ID), and the `js/` prefix gets repeated when using the loader (eg. `/js/js/0.d32a0b797e13ff4d9fff.en.js`). I dug into this but there didn't seem anything wrong with `esbuild-loader` -- I think it's a Webpack bug:
  - If I return the source code given (unaltered) via async callback, it works fine
  - I inspected the transpiled code given by esbuild, but nothing stuck out as being problematic

  Might look into it more later.

- Doing the transpilation at the end with the minifier yields better results. Minor but definitely in terms of size, probably because the polyfills aren't repeated for every file that needs it. It might be worth just making this a plugin.

I'm okay with merging this for now and addressing these points later. WDYT?

**Comment by privatenumber** [comment]
I figured why the loader was being problematic. It's because esbuild strips comments even when not minifying, which strips [Webpack magic comments](https://webpack.js.org/api/module-methods/#magic-comments).

```diff
-main: () => import(
-/* webpackChunkName: "chunk-name" */
-'../chunk-name'
-),
+main: () => import("../chunk-name")
```

Edit:
Submitted a feature request here https://github.com/evanw/esbuild/issues/309

**Comment by privatenumber** [comment]
Going to move forward with this because it's an external issue and this isn't a regression.

**Pull request merged**
