### PR TITLE
feat: upgrade esbuild

### PR DESCRIPTION
**Pull request by g-plane**
I wish "esbuild" can be a peer dependency, which will allow users to upgrade by themselves.

### CODE REVIEW

**Comment by privatenumber** [comment]
Please read: https://github.com/privatenumber/esbuild-loader#bring-your-own-esbuild-advanced

**Comment by g-plane** [comment]
I know, but I don't think that will prevent this PR.

**Comment by privatenumber** [comment]
Why's that?

**Comment by g-plane** [comment]
That will require additional configurations, which most people won't notice that. Also, that will introduce two or more "esbuild" installations in `node_modules` directory.

**Comment by privatenumber** [comment]
If those are the only motivations you have to make this PR, I think it's preventable.

Majority of users don't care about using the latest esbuild; they're just happy with the speed benefits. Amongst those that do care, the majority are happy with the `implementation` API. It's rare that someone feels compelled by a package duplication in `node_modules`.


JSYK I understand the benefits of having it as a peer dependency, and it will be in the future. In case you missed it in the readme:
> _The `implementation` option will be removed once esbuild reaches a stable release. Instead esbuild will become a peerDependency so you always provide your own._

Currently, the maintenance cost I would take by expecting users to understand npm's major-zero semver and how it's different from normal semver is too high. Having this road-block actually saves me time at a small cost to the API.

**Comment by vgpechenkin** [comment]
Hi,
I try to use custom esbuild (0.13.x version). But on CI I have a problem with downloading platform-specific version esbuild (https://github.com/privatenumber/esbuild-loader/issues/206).
It has been fixed in 0.13 version.
Thanks

**Comment by privatenumber** [comment]
That's a good motivation. Thanks for sharing it!

Will try to release tomorrow. Sorry, its late here.

(Don't hesitate to request an upgrade in the future, especially if theres a problem. I'm not against it, just busy.)

**Pull request merged**
