### PR TITLE
chore: upgrade esbuild to v0.10.2

### PR DESCRIPTION
**Pull request by privatenumber**

### CODE REVIEW

**Comment by josteph** [comment]
@privatenumber is there any benchmark prior the upgrade to `0.10.2` ?

**Comment by privatenumber** [comment]
@josteph All benchmarks shared [here](https://github.com/privatenumber/esbuild-loader/issues/13) are prior to this upgrade

**Comment by josteph** [comment]
@privatenumber i meant the benchmark to compare 0.9.x vs 0.10.x

I honestly just tried 0.10.x and I've seen huge amount of performance declines in comparison to 0.9.x. Have you personally tested it?

**Comment by privatenumber** [comment]
I didn't notice any. What are the differences you're seeing?

Edit:
These are trivial examples but there are no performance regressions [here](https://github.com/privatenumber/esbuild-loader-examples/pull/1).

**Comment by josteph** [comment]
@privatenumber I'll see if I can create a small reproduction of the perf regression, most likely due to using typescript (hopefully not).

**Pull request merged**
