### PR TITLE
feat: support transform imports

### PR DESCRIPTION
**Pull request by richardchen85**
Support transform imports like `babel-plugin-transform-imports` does

### CODE REVIEW

**Comment by privatenumber** [comment]
What for?

Also:
- Please start with an Issue next time
- No regex based analysis/transformations

**Comment by ghost** [comment]
We also need this feature, is it possible to continue the work?
Thanks

**Comment by richardchen85** [comment]
@chengjiaapraamcos Unfortunately, I deleted the code. My code is based on regex analysis, which is not allowed by this repo.

**Comment by privatenumber** [comment]
In general, opening a PR without an explanation will never get approved. Based on #260, this feature is irrelevant to esbuild and doesn't make sense to be in this project.

Although it's out of scope, I encourage you to make your own Webpack loader with it and just chain it in your configuration.

BTW, your code isn't deleted. It's still viewable in this PR. But yeah, regex is not reliable. You should use [es-module-lexer](https://github.com/guybedford/es-module-lexer) instead.

**Pull request closed without merging**
