### PR TITLE
feat: upgrade esbuild to v0.18

### LINKED ISSUE #326: esbuild 0.18
### Feature request

esbuild 0.18 has been out for a while, it should be upgraded. As far as I can tell, it should be a smooth upgrade with little breaking changes.

https://github.com/evanw/esbuild/blob/main/CHANGELOG.md

### Why?

Keep up with latest features and bug fixes.

### PR DESCRIPTION
**Pull request by privatenumber**
closes https://github.com/esbuild-kit/esbuild-loader/issues/326

### CODE REVIEW

**Comment by Davidcreador** [comment]
Thanks for this! 🎉

**Comment by n-rodriguez** [comment]
hi there! any news?

**Comment by n-rodriguez** [comment]
Thank you!

**Pull request merged**
