### PR TITLE
Add flatMap() fallback; fixes #26

### LINKED ISSUE #26: Implement flatMap fallback for better Node.js compatibility
The `flatMap` Array method has only been introduced in Node 11, but Node 10 [will be still around until (at least) 2021](https://nodejs.org/en/about/releases/). I propose a simple fallback for the missing method, to make the loader compatible with more Node.js versions:

```diff
diff --git a/src/minify-plugin.js b/src/minify-plugin.js
index 7916f1e..1e8e83f 100644
--- a/src/minify-plugin.js
+++ b/src/minify-plugin.js
@@ -3,6 +3,8 @@ const { RawSource, SourceMapSource } = require('webpack-sources')
 const isJsFile = /\.js$/i
 const pluginName = 'esbuild-minify'
 
+const flatMap = (arr, cb) => arr.flatMap ? arr.flatMap(cb) : [].concat(...arr.map(cb))
+
 class ESBuildMinifyPlugin {
   constructor(options) {
     this.options = { ...options }
@@ -39,7 +41,7 @@ class ESBuildMinifyPlugin {
       compilation.hooks.optimizeChunkAssets.tapPromise(
         pluginName,
         async (chunks) => {
-          const transforms = chunks.flatMap((chunk) => {
+          const transforms = flatMap(chunks, (chunk) => {
             return chunk.files
               .filter((file) => isJsFile.test(file))
               .map(async (file) => {

```

If there's interest in this, I can make a PR.

### PR DESCRIPTION
**Pull request by danburzo**
As discussed in #26, a simple fallback for flatMap().

### CODE REVIEW

**Comment by privatenumber** [comment]
Thanks @danburzo 

Can you also add Node 10 to the CI tests?
https://github.com/egoist/esbuild-loader/blob/master/.github/workflows/nodejs.yml#L19

**Comment by danburzo** [comment]
Sure thing, added in the commit above.

**Comment by egoist** [comment]
Just changed the base branch to develop in repo settings so @privatenumber doesn't need to do that manually again.

**Review by egoist — APPROVED** [review]

**Comment by privatenumber** [comment]
Thank you both! 🙏

**Comment by privatenumber** [comment]
Little mistake. I think the semantic release gets run in both Node 10 and 14.

**Pull request merged**
