### PR TITLE
docs: Added minify:true to EsbuildPlugin

### PR DESCRIPTION
**Pull request by Alex-Sokolov**
After last update (https://github.com/esbuild-kit/esbuild-loader/pull/333) needed to explicit turn on minification

### CODE REVIEW

**Comment by privatenumber** [comment]
It doesnt if its passed into optimization.

Are you experiencing different behavior?

**Comment by Alex-Sokolov** [comment]
I use production config with `mode: 'production'`. And webpack runs optimizations for you depending on the chosen mode. Before update I got minified files automatically, after update files not minified when building for production until I add minify to EsbuildPlugin. I think that needed be clarified in docs

**Comment by privatenumber** [comment]
Sounds like a bug.

See the tests for expected behavior.

Would you mind sharing your configuration to demonstrate the behavior you're setting?

**Comment by privatenumber** [comment]
Here's the base repro template from the Bug report form.

You can see that the distribution is minified despite `minify: true` not being passed in:
https://stackblitz.com/edit/node-guv65j?file=dist%2Fmain.js&view=editor

Closing for now but feel free to provide more information or file a bug report if you can reproduce it.

**Comment by Alex-Sokolov** [comment]
Thanks for template!

Finally after work have a time to make a repro :) @privatenumber could you take a look?
https://stackblitz.com/edit/node-bexr5c?file=dist%2Fmain.js

When use esbuild-loader@3.1.0
Снимок экрана 2023-08-18 в 23 24 04

When use esbuild-loader@4.0.0
Снимок экрана 2023-08-18 в 23 24 26

**Comment by privatenumber** [comment]
Thanks, I've verified. This isn't really a bug but it's an inaccuracy caused by webpack-merge duplicating objects.

Will fix soon.

Next time, please start by filing an issue.

**Pull request closed without merging**
