### PR TITLE
[esbuild] version 11

### PR DESCRIPTION
**Pull request by natew**

### CODE REVIEW

**Comment by privatenumber** [comment]
Thanks for the esbuild upgrade.

Is there a specific reason you're looking to get v11? eg. a feature/bugfix.

A new version of esbuild is released every other day, so I'm hesitant to do just upgrade for the sake of upgrading.

As for the failing test, it should be fixed if you pull in `develop`.

**Comment by eliseumds** [comment]
@privatenumber shouldn't `esbuild@11.x` become a peer dependency? That would allow end users to upgrade seamlessly and would prevent the creation of tickets like this one.

**Comment by privatenumber** [comment]
@eliseumds 

Currently, esbuild is unstable/major-zero (has dramatic implementation/output changes and can make breaking changes without a major bump), so esbuild-loader comes with a specific version of esbuild that's been tested to work.

Once esbuild is stable, esbuild-loader will do a major release to convert esbuild to a peer dependency.

**Comment by tebuevd** [comment]
@privatenumber doesn't `"esbuild": "^0.10.2"` mean _any minor or patch version above 0.10.2_ ? I think you want `~0.10.2` to have it stick to minor version 10.

**Comment by privatenumber** [comment]
@tebuevd 

That's correct for any stable semver version, but for major-zero, `^0.10.0` and `~0.10.0` [are the same](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004:~:text=%5E0.2.3%20%3A%3D%20%3E%3D0.2.3%20%3C0.3.0).


You can confirm this behavior by installing `esbuild-loader` from scratch. It will install esbuild `0.10.2`.

**Comment by eliseumds** [comment]
What about being able to pass a custom esbuild like [sass-loader](https://github.com/webpack-contrib/sass-loader#implementation)?

**Comment by privatenumber** [comment]
Happy to discuss this further but this is not the right place for it.

Can you open a feature request?

**Comment by privatenumber** [comment]
Resolved via https://github.com/privatenumber/esbuild-loader/pull/153

**Pull request closed without merging**
