### PR TITLE
fix: move webpack to dependency for ts

### PR DESCRIPTION
**Pull request by escapedcat**
I moved both Webpack versions to dependency otherwise people using v5 might run into issues?
I also had to update the jest-snapshots. Hope this is correct.

### CODE REVIEW

**Comment by escapedcat** [comment]
@privatenumber let me know if I can improve something. Happy to help.

**Comment by privatenumber** [comment]
I started looking into this last night but trying to reproduce the issue in a minimal environment so I can test with it, and also test future changes as well. I've never used a TS webpack config before so was just reading up on that.

If your repo is public do you mind sharing it? It would speed things up a lot. If not, I'll try to work on a minimal repro this weekend -- would appreciate any help on this too if you have time!

**Comment by escapedcat** [comment]
@privatenumber hope this helps:  
https://github.com/escapedcat/esbuild-loader-webpack4-type-issue

**Comment by privatenumber** [comment]
Amazing! Thank you so much. I'll try it out tonight.

**Comment by privatenumber** [comment]
Thanks @escapedcat that was really helpful.

This was just released in 2.6.2

**Comment by escapedcat** [comment]
@privatenumber thanks a lot! 🎉

**Comment by WearyMonkey** [comment]
After this change I get:

```
error An unexpected error occurred: "could not find a copy of webpack to link in /Users/toby/dev/canva/web/node_modules/esbuild-loader/node_modules".
```

When yarn installing into a project with webpack 5.

Installing `yarn add esbuild-loader@2.6.1` works though.

Also, I'm not sure this change is a good move. It means all webpack 5 projects will download a copy of webpack 4 which is pretty heavy.

**Comment by escapedcat** [comment]
Ugh! Sorry @WearyMonkey  
@privatenumber here you find a branch to reproduce this issue: https://github.com/escapedcat/esbuild-loader-webpack4-type-issue/tree/webpack5  

**Edit:** Looks like the issue in the repo is different to the one from the comment.


@WearyMonkey not sure if it's possible to solve this typing issue for both versions without installing both of them. Maybe this package should exists for both versions separately or create new major versions which only supports webpack5? I'm pretty new to TS. No idea if there's a nicer ways to solve this.

**Comment by WearyMonkey** [comment]
You could use `@types/webpack` for webpack 4, and maybe encourage them to add the v5 types as well.

Or you could not use the webpack types, and just manually type the parts you need, e.g.:

```
interface LoaderContext {
  async(): (err: any, source?: string | Buffer, map?: any) => void;
}

async function ESBuildLoader(
	this: LoaderContext,
	source: string,
) {
```

**Comment by privatenumber** [comment]
Fixed in v2.6.3 via https://github.com/privatenumber/esbuild-loader/pull/78

Wepback 5 won't be supported with types but [LMK if you have any ideas](https://twitter.com/privatenumbr/status/1338787270938255361?s=20) on how to solve the problem in the PR. If there's a way to conditionally import or fallback types, that would solve it.

**Pull request merged**
